### ISSUE TITLE
Usage with shadow-cljs

### ISSUE THREAD

**Issue by rome-user** [pitch-io/cljest#26]
Hello,

I am wondering if documentation could be provided on using this with shadow-cljs. Karma, for instance, has a dedicated `:target` in Shadow CLJS. Is there a certain target needed for Jest, or does it suffice to use something like `:node-script` with `:js-provider :external`?

Thank you

**Comment by diegoatpitch** [comment]
I am not 100% on this but `cljest` does use shadow-cljs for running your tests.
There is no configuration needed on shadow-cljs because it will be [generated](https://github.com/pitch-io/cljest/blob/a84b9df15df3a0813094a52ff00ca0bd8b255dd0/cljest/src/cljest/compilation/shadow.clj#L202C22-L218) for you.

Any customization you need, you can do with `cljest.edn`. If you are missing an specific option you can raise a feature request for that too.

**Comment by diegoatpitch** [comment]
You are right that it's not mentioned in the docs. Explaining it in a "shadow-cljs" section would make things clearer :+1:
