### ISSUE TITLE
Integration with existing shadow-cljs.edn file

### ISSUE THREAD

**Issue by rafaeldelboni** [pitch-io/cljest#52]
Hey there! I've been digging into cljest and its integration with shadow-cljs. I noticed that cljest manages its [own shadow-cljs configuration separately](https://github.com/pitch-io/cljest/blob/master/cljest/src/cljest/compilation/shadow.clj) from an existing `shadow-cljs.edn` file.

I'd love to integrate cljest's build and test processes with my existing `shadow-cljs.edn` and be able to have my dev server and test watch running in one shadow command.

**Comment by jo-sm** [comment]
Hey there, sorry for the really delayed response. So unfortunately I don't think this is really possible due to the way that `cljest` and `shadow-cljs` work together (or at least would cause some dev-ex friction). In general the way that I've set it up is that I want Jest to be in control of the FS watching and subsequent compilation triggering (since it's not possible to control this on the Jest side, and having two FS watchers often ran into race conditions), and while it's possible to run `shadow-cljs` in a "headless" mode such that you can manually trigger a compilation, when I tried to get it working so that it would work identically to `watch` mode without a watcher instance, it didn't seem to work as expected and so I had to do a lot of workarounds to get them to play well together, mainly overriding the way that `shadow-cljs` deals with watching and its config. So long story short having it integrate where shadow is the one that drives the process is kind of a no-go with Jest.

That said, I don't think they should clash, and one thing I thought about is taking parts of the config and merging them into the internal config so that there's less friction there. Do you think this would be helpful in your case?

**Comment by rafaeldelboni** [comment]
Thanks for the clarification
